name: Get OHL Rosters

on:
  schedule:
    # Schedule the workflow for the desired times (adjusting for UTC offsets)
    - cron: "0 17 * * *"  # 12:00 PM EST (5:00 PM UTC) (01:00 PM EDT)
    - cron: "0 22 * * *"  # 5:00 PM EST (10:00 PM UTC) (06:00 PM EDT)
    - cron: "0 9 * * *"   # 4:00 AM EST (9:00 AM UTC) (05:00 AM EDT)
  workflow_dispatch:

jobs:
  fetch_rosters:
    runs-on: ubuntu-latest

    steps:
      - name: Log Start Time
        run: |
          echo "Workflow started at: $(date -u)" >> $GITHUB_STEP_SUMMARY

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.1

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run the Roster Scraper
        run: |
          start_time=$(date +%s)
          python get_rosters.py > scraper_log.txt 2>&1
          end_time=$(date +%s)
          duration=$((end_time - start_time))
          echo "Workflow runtime: $((duration / 60)) minutes and $((duration % 60)) seconds." >> $GITHUB_STEP_SUMMARY

      - name: Verify CSV File Exists
        run: |
          if [ ! -f "OHL_ROSTERS_2024_2025.csv" ]; then
            echo "Error: CSV file not generated!";
            exit 1;
          fi

      - name: Archive Old CSV
        run: |
          mkdir -p OHL_ROSTERS_ARCHIVE
          if [ -f OHL_ROSTERS/OHL_ROSTERS_2024_2025.csv ]; then
            timestamp=$(date +%Y%m%d_%H%M%S)
            mv OHL_ROSTERS/OHL_ROSTERS_2024_2025.csv OHL_ROSTERS_ARCHIVE/OHL_ROSTERS_2024_2025_${timestamp}.csv
          fi

      - name: Move New CSV to Folder
        run: |
          mkdir -p OHL_ROSTERS
          mv OHL_ROSTERS_2024_2025.csv OHL_ROSTERS/

      - name: Check for Changes
        run: |
          if git diff --quiet; then
            echo "No OHL Roster changes. Exiting Successfully..." >> $GITHUB_STEP_SUMMARY
            exit 0;
          else
            echo "Changes detected in OHL Rosters. Preparing to commit these..." >> $GITHUB_STEP_SUMMARY
            git diff --stat >> $GITHUB_STEP_SUMMARY
          fi

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add OHL_ROSTERS/OHL_ROSTERS_2024_2025.csv
          git add OHL_ROSTERS_ARCHIVE/
          git commit -m "Automated update: OHL Rosters CSV and archive"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

