name: Daily Roster Scraper

on:
  schedule:
    # Schedule the script to run daily at 22:45 PM EST (03:45 AM UTC)
    - cron: '55 3 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape_rosters:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install requests pandas

      # Step 4: Run the Python script
      - name: Run roster scraper
        run: python get_rosters.py

      # Step 5: Commit and push the CSV file to the repository
      - name: Commit and push CSV
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add rosters_updated.csv
          git commit -m "Update rosters_updated.csv [skip ci]"
          git push

